version: '3.7'
services:
  consul:
    image: bitnami/consul:latest
    ports:
      - "8500:8500"
    volumes:
#      - ./consul/ckad-local:/bitnami
#      - ./consul/m12-dev:/bitnami
#      - ./consul/sopt-dev:/bitnami
#      - ./consul/obscur-local:/bitnami
      - ./consul/sso-local:/bitnami