version: '3.7'
services:
  grafana:
    image: grafana/grafana-oss:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-storage/data:/var/lib/grafana
#      - ./grafana-storage/config:/etc/grafana
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel, grafana-piechart-panel'
      GF_SERVER_ROOT_URL: 'http://localhost:3000/'
      GF_SECURITY_ADMIN_USER: user
      GF_SECURITY_ADMIN_PASSWORD: password

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
#    ports:
#      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - ext

networks:
  ext:
    name: ext
    external: true