version: '3.7'
services:
  timescale:
    image: timescale/timescaledb:latest-pg14
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - timescale-volume:/var/lib/postgresql/data

volumes:
  timescale-volume: #