version: '3.7'
services:
  postgres:
    image: postgis/postgis:14-3.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres